Admin controller, user & admin dao, view's javascript & model views with models
OTAL2020/Lmaoo pull request #10
Opened 2022-01-11 19:26 UTC by LewisWelch94

2022-01-11 21:12 UTC, OnikNoor97 requested changes
We will go over this tomorrow. Good work so far!

2022-01-11 21:12 UTC, OnikNoor97 commented on Otal.lmaoo.Services/Interfaces/IAdminService.cs
> +    using Otal.lmaoo.Core.Entities;
Add new line

2022-01-11 21:12 UTC, OnikNoor97 commented on Otal.lmaoo.Services/ServiceObjects/AdminServices.cs
> +    public class AdminService : IAdminService
New line here

2022-01-11 21:12 UTC, OnikNoor97 commented on Otal.lmaoo.Services/ServiceObjects/AdminServices.cs
> +            return _userDao.UpdateUser(Username, Forename, Surname, Level, IsActive);
Instead of different 5 parameters. Use the User object

2022-01-11 21:12 UTC, OnikNoor97 commented on Otal.lmaoo.Services/ServiceObjects/AdminServices.cs
> +            return _userDao.DeactivateUser(IsActive);
Where's activate user? Also isActive is redundant here. Just put 0 directly as a parameter

2022-01-11 21:12 UTC, OnikNoor97 commented on Otal.lmaoo.Web/Controllers/AdminController.cs
> +            return View(vm);
Why do we need return URL here?

2022-01-11 21:12 UTC, OnikNoor97 commented on Otal.lmaoo.Web/Controllers/AdminController.cs
> +        public IActionResult IsActiveSelect(AdminViewModel vm)
Remove this method entirely. Not required

2022-01-11 21:12 UTC, OnikNoor97 commented on Otal.lmaoo.Web/Controllers/AdminController.cs
> +            var user = vm.UserId;
var UserId. Not user

2022-01-11 21:12 UTC, OnikNoor97 commented on Otal.lmaoo.Web/Controllers/AdminController.cs
> +        public IActionResult getUserByIsActive(AdminViewModel vm)
Why is it post when we're getting a list of users?

2022-01-11 21:12 UTC, OnikNoor97 commented on Otal.lmaoo.Web/ViewModels/AdminViewModel.cs
> +        public string ReturnUrl { get; set; }
We will review this view model tomorrow

2022-01-11 21:12 UTC, OnikNoor97 commented on Otal.lmaoo.Web/ViewModels/CreateTicketProjectViewModel.cs
> +
Should be createProjectViewModel. The page name shouldn't matter as the location of the cshtml says where it is

2022-01-11 21:12 UTC, OnikNoor97 commented on Otal.lmaoo.Web/ViewModels/EditAdminViewModel.cs
> +
Same as above

2022-01-11 21:12 UTC, OnikNoor97 commented on Otal.lmaoo.Web/ViewModels/EditFeatureProjectViewModel.cs
> +
Same as above

2022-01-11 21:12 UTC, OnikNoor97 commented on Otal.lmaoo.Web/ViewModels/EditPasswordProfileViewModel.cs
> +
Same as above

2022-01-11 21:12 UTC, OnikNoor97 commented on Otal.lmaoo.Web/ViewModels/EditProjectManagerViewModel.cs
> +
Same as above

2022-01-12 11:51 UTC, LewisWelch94 commented on Otal.lmaoo.Web/Controllers/AdminController.cs
> +        public IActionResult getUserByIsActive(AdminViewModel vm)
remove

2022-01-12 11:51 UTC, LewisWelch94 commented on Otal.lmaoo.Web/ViewModels/AdminViewModel.cs
> +        public string ReturnUrl { get; set; }
remove

2022-01-12 11:52 UTC, LewisWelch94 commented on Otal.lmaoo.Web/Controllers/AdminController.cs
> +            return View(vm);
remove

2022-01-12 11:52 UTC, LewisWelch94 commented on Otal.lmaoo.Services/ServiceObjects/AdminServices.cs
> +            return _userDao.DeactivateUser(IsActive);
make into 1 function

2022-01-12 14:15 UTC, OnikNoor97 requested changes

2022-01-12 14:15 UTC, OnikNoor97 commented on Otal.lmaoo.Database/dbo/Stored Procedures/User_EditUserActiveStatus.sql
> +﻿CREATE PROCEDURE [dbo].[User_DeactivateUser]
User_Edit_isActive

2022-01-12 14:15 UTC, OnikNoor97 commented on Otal.lmaoo.Database/dbo/Stored Procedures/User_GetByactive.sql
> +﻿CREATE PROCEDURE [dbo].[User_GetByactive]
User_GetByActive
-> Missing Capital 'a'
Dont forget to also rename the file

2022-01-12 14:34 UTC, merged